LTSI: bugfix: add CONFIG_I2C to kzm9g_defconfig
Build fails for kzm9g because CONFIG_I2C=y is missing in kzm9g_defconfig.

$ make kzm9g_defconfig
$ make

  ...

  CC      arch/arm/mach-shmobile/board-kzm9g.o
arch/arm/mach-shmobile/board-kzm9g.c: In function 'as3711_enable_lcdc_backlight':
arch/arm/mach-shmobile/board-kzm9g.c:314:9: error: implicit declaration of function 'i2c_get_adapter' [-Werror=implicit-function-declaration]
arch/arm/mach-shmobile/board-kzm9g.c:314:26: warning: initialization makes pointer from integer without a cast [enabled by default]
arch/arm/mach-shmobile/board-kzm9g.c:349:3: error: implicit declaration of function 'i2c_transfer' [-Werror=implicit-function-declaration]
cc1: some warnings being treated as errors
make[1]: *** [arch/arm/mach-shmobile/board-kzm9g.o] Error 1
make: *** [arch/arm/mach-shmobile] Error 2

This patch solves this problem.

Signed-off-by: Tetsuyuki Kobayashi <koba@kmckk.co.jp>