AXFS: fix build failure due to undefined symbol axfs_xip_record()
This patch fixes following build failure when axfs is compiled
as a module. The build failure is caused by
Commit-ID: a7e526129f6ea298513ef4ce7aa6db08fc069d14

ERROR: "axfs_xip_record" [fs/axfs/axfs.ko] undefined!

Signed-off-by: Aaditya Kumar <aaditya.kumar@ap.sony.com>