arm: fix compile failure in mach-shmobile/board-ag5evm.c
Add videodev2 header which provides V4L2_PIX_FMT_RGB565 to fix:

arch/arm/mach-shmobile/board-ag5evm.c:274: error: 'V4L2_PIX_FMT_RGB565' undeclared here (not in a function)

Signed-off-by: Paul Gortmaker <paul.gortmaker@windriver.com>
Signed-off-by: Paul Mundt <lethal@linux-sh.org>
(cherry picked from commit 04f47a03c51c9f02fa27b0ecf4207e25c0741804)

Signed-off-by: Simon Horman <horms@verge.net.au>