mtd: atmel_nand: fix the compile error which miss label "err_ecc_ioremap"
Add err_ecc_ioremap label to fix following errors:
---8<---
  CC      drivers/mtd/nand/atmel_nand.o
drivers/mtd/nand/atmel_nand.c: In function 'atmel_nand_probe':
drivers/mtd/nand/atmel_nand.c:1423: error: label 'err_ecc_ioremap' used but not defined
make[3]: *** [drivers/mtd/nand/atmel_nand.o] Error 1
make[2]: *** [drivers/mtd/nand] Error 2
make[1]: *** [drivers/mtd] Error 2
make: *** [drivers] Error 2
--->8---

This error was introduced in b654a9a46fc2100b318050483f8c5b5d0f187303 (mtd: atmel nand: fix gpio missing request)

Signed-off-by: Josh Wu <josh.wu@atmel.com>
Signed-off-by: Jean-Christophe PLAGNIOL-VILLARD <plagnioj@jcrosoft.com>